### ISSUE TITLE
Feature: Do not show the "brand" banner for components which have no branding whatsoever

### ISSUE THREAD

**Issue by JakeChampion** [Financial-Times/origami-registry-ui#152]
## Feature request
Let's not show the brand banner for components such as [o-expander](https://registry.origami.ft.com/components/o-expander@4.6.1) because they have no real need for brand specific styling.

## What
Some people, like me, might think they can not use a component because it is not branded and the banner makes them think that they need to get the component branded before using it. Some components require no branding whatsoever because they do not carry brand-specific styling. Those components should not show the brand banner at all, to ensure people like me do not get confused.

**Comment by notlee** [comment]
If a component is not branded it may fail to compile for any non-master brand unexpectedly (now or in a future patch/minor). Instead if the component doesn't need branding we should list the brands as support in `origami.json` to remove the message.

**Comment by notlee** [comment]
E.g. :) https://github.com/Financial-Times/o-expander/pull/66

**Comment by JakeChampion** [comment]
Clever! I agree. Shall we close this ticket?
