### ISSUE TITLE
Select full code snippet blocking html

### ISSUE THREAD

**Issue by chivchila** [Financial-Times/origami-registry-ui#233]
A small issue

## What

When looking at html examples of the origami components sometimes I come across cases where html code is blocked by the "Select full code snippet" button on the top right. This isn't a problem for the html that is bigger and can be scrolled to the right. In some smaller html code fragments html code is not visible

## Details

<img width="630" alt="Screenshot 2020-02-12 at 14 41 03" src="https://user-images.githubusercontent.com/14136353/74346058-e92a6100-4da6-11ea-9c21-940097515165.png">
<img width="618" alt="Screenshot 2020-02-12 at 14 51 00" src="https://user-images.githubusercontent.com/14136353/74346265-373f6480-4da7-11ea-8fe8-064db8ae2c05.png">

**Comment by notlee** [comment]
Thanks for the detailed issue! I moved this to `origami-registry-ui` which is where the origami registry styles live

**Comment by chee** [comment]
How do we feel about it sitting outside the `<pre/>`?
![screenshot](https://user-images.githubusercontent.com/178266/74563591-07d65680-4f65-11ea-8e10-3cd8ea3e69ac.png)
