### ISSUE TITLE
Work out how we show whether a component has JS, CSS, or both

### ISSUE THREAD

**Issue by rowanmanning** [Financial-Times/origami-registry-ui#28]
Currently this uses a build service endpoint that doesn't exist in v3 of the Build Service. We need to to work out whether this is useful information to display and then how we're going to implement in the new Build Service.

I think it's fine to launch without this work being done.

**Comment by gvonkoss** [comment]
This is mentioned in specific places in the code under `TODO`, where we're going to need it.

**Comment by rowanmanning** [comment]
This has been added to repo data in https://github.com/Financial-Times/origami-repo-data/pull/76 - we can use the new `languages` property to determine this.
