### ISSUE TITLE
Work out how we display whether a version of a component builds or not

### ISSUE THREAD

**Issue by rowanmanning** [Financial-Times/origami-registry-ui#30]
Currently this uses a build service endpoint that doesn't exist in v3 of the Build Service. We need to to work out whether this is useful information to display and then how we're going to implement in the new Build Service.

I think it's fine to launch without this work being done.

**Comment by rowanmanning** [comment]
Removing this from the launch milestone as I don't think it's required

**Comment by chee** [comment]
We don't publish tags unless the build passed, so i don't think we need this
