### ISSUE TITLE
Improve Origami service discoverability

### ISSUE THREAD

**Issue by notlee** [Financial-Times/origami-registry-ui#397]
Its not always easy to jump to the documentation of an Origami Service as pointed out
by [Rhys in Slack](https://financialtimes.slack.com/archives/C02FU5ARJ/p1597146750154700). I never remember the urls and also find it difficult sometimes!

The quickest way to a list of services and their documentation is ok:
`origami.ft.com > docs > services`

But the registry route is cumbersome, as Rhys explains:
>That is not the route I used. I went registry, change filters (3 clicks), image service, then click the correct link (one out of about 12) to get to the service docs

## Proposal

We could improve the registry route by making the search better. Maybe we should consider:

- default the "types" filter to all things, so searching a service name returns results by default
- update the types filter to a radio input, so limiting by type is one click (is filtering multiple types useful?)
- improve the search "image service" with all types selected returns no results why!?

## Alternatives

Add a new top level heading to the [services overview docs](https://origami.ft.com/docs/services/):
- It would solve nicely, services would be very discoverable.
- The breadcrumbs on the docs page wouldn't match, would it be confusing alongside the docs section?
- Note: don't forget to update [origami-website](https://github.com/Financial-Times/origami-website/) for this option

Do nothing:
- Component users searching for components in the registry get the best experience at the expense of service users looking for service documentation via the registry.

**Comment by JakeChampion** [comment]
> improve the search "image service" with all types selected returns no results why!?

This has been solved thanks to @chee's work on [origami-repo-data](https://github.com/Financial-Times/origami-repo-data/releases/tag/v136.1.0)
