### ISSUE TITLE
Hide deprecated/experimental/dead in component list

### ISSUE THREAD

**Issue by gvonkoss** [Financial-Times/origami-registry-ui#53]
But allow the search functionality to find those components.

**Comment by rowanmanning** [comment]
Removing from launch milestone as we match the behaviour of the existing registry already. We can add after launch

**Comment by notlee** [comment]
We now default to having deprecated/experimental/dead hidden from the filter which I think covers this issue.
![Screenshot 2019-05-29 at 08 50 16](https://user-images.githubusercontent.com/10405691/58539233-cf33f880-81ee-11e9-87a3-572ee1592cc9.png)
