### ISSUE TITLE
Add anchors for section headers

### ISSUE THREAD

**Issue by jonnywyatt** [Financial-Times/origami-registry-ui#57]
It would be extremely useful to be able to have anchor IDs for each main section heading within a page so we can share URLs for discussion etc. Maybe show a link icon when hovering over the heading?

**Comment by gvonkoss** [comment]
Just to clarify, you mean by the headers of the demos?

**Comment by jonnywyatt** [comment]
Yes, or any major subsection of the page, so it can be shared with an # anchor in the URL

![image](https://user-images.githubusercontent.com/471250/36801182-40e49504-1ca9-11e8-914e-499858a38f76.png)
